name: SSH Deploy

on:
  push:
    branches: [ main ]

jobs:
  job_one:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: ssh git server deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 202.52.248.109
        username: man_svr
        key: ${{ secrets.SSH_PRIVATE_KEY_MAIN }}
        port: 2050
        script: |
          cd /var/www/marineaquatics.com.np
          sudo -H -u man_svr git pull 
          sudo -H -u man_svr npm run prod-admin
          sudo -H -u man_svr npm run prod-site
          sudo -H -u man_svr php artisan cache:clear
