name: SSH Deploy

on:
  push:
    branches: [ main ]

jobs:
  job_one:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: ssh git server deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 110.44.121.123
        username: marineaquatics
        key: ${{ secrets.SSH_PRIVATE_KEY_MAIN }}
        port: 2050
        script: |
          cd /home/marineaquatics/www/marineaquatics.com.np
          git pull
          npm run prod-admin && npm run prod-site
